# Send a chat message : Post()
# Chat history : get()
# Robot live status : get()
# Current mission status : get()
# Return to docking station : Post()
# Begin perimeter scan : post()
# Share laser alerts : get()
# start recording : post()
# stop & convert to text : post ()
