# Robot Bags Tree : get()
# download robot bags : get()
# Robot Bags List : get()
# Send Robot to Waypoint : post()
# Upload Bags : Post ()
# processing status : get()
#  download a bag file : get()
#  Change metadata : put()
# Delete a bag file : delete()