# overall stats : get()
# monthly movement : get ()
# Power & voltage time series : get ()
# turn distribution : get()
# mission trend : get ()
#  total moving distance : get ()
# missions completed : get ()
# average speed : get ()
#  operating hours : get ()
# battery- telemetry : get()
